/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IUser = t.iface([], {
  "favorite_exercise": t.opt("string"),
  "country": t.opt("string"),
  "usrName": "string",
  "name": t.iface([], {
    "first": "string",
    "last": "string",
  }),
  "age": t.opt("number"),
});

const exportedTypeSuite: t.ITypeSuite = {
  IUser,
};
export default exportedTypeSuite;
