/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IFindByNameURLQuery = t.iface([], {
  "first": t.opt("string"),
  "last": t.opt("string"),
});

export const IFindByCountryURLQuery = t.iface([], {
  "country": t.opt("string"),
  "order": t.opt(t.iface([], {
    "field": "string",
    "directions": t.opt(t.union(t.lit('asc'), t.lit('des'))),
  })),
});

const exportedTypeSuite: t.ITypeSuite = {
  IFindByNameURLQuery,
  IFindByCountryURLQuery,
};
export default exportedTypeSuite;
