/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IFindByNameURLQuery = t.iface([], {
  "first": t.opt("string"),
  "last": t.opt("string"),
});

export const IFindByCountryURLQuery = t.iface([], {
  "country": "string",
});

export const IRegisterUserReferenceIUser = t.iface([], {
  "favorite_exercise": t.opt("string"),
  "country": t.opt("string"),
  "usrName": "string",
  "name": t.iface([], {
    "first": "string",
    "last": "string",
  }),
  "age": t.opt("number"),
});

const exportedTypeSuite: t.ITypeSuite = {
  IFindByNameURLQuery,
  IFindByCountryURLQuery,
  IRegisterUserReferenceIUser,
};
export default exportedTypeSuite;
